[application]

# App (Project) Name
name = "invite"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# base path for github pages
# base_path = "invite"

# HTML title tag content
title = "invite"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = [
  "//dapi.kakao.com/v2/maps/sdk.js?autoload=true&appkey=850d92aa29afbf5806173cc1985cbb67"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
