name: Publish Github Page

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install Dioxus-CLI
        shell: bash
        run: cargo install dioxus-cli

      - name: Setup Base Path
        shell: bash
        run: sed -i 's/# base_path/base_path/' ./Dioxus.toml

      - name: Build Project
        env:
          INVITATION_CODE: ${{ secrets.INVITATION_CODE }}
          LDAP_LIST: ${{ secrets.LDAP_LIST }}
        shell: bash
        run: dx build --release && cp ./target/dx/invite/release/web/public/index.html ./target/dx/invite/release/web/public/404.html

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./target/dx/invite/release/web/public
          clean: false
